name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 0.12.1+1
homepage: https://github.com/brianegan/chewie

environment:
  sdk: ">=2.11.5 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  video_player:
    git:
      url: https://github.com/KurdAppDev/plugins.git
      path: 'packages/video_player/video_player'
      ref: master
  wakelock: ^0.5.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
